services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-web-dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:3000/api"
      CHOKIDAR_USEPOLLING: "true"
      HOST: "0.0.0.0"
      PORT: "5173"
    volumes:
      - .:/app
    command: >
      sh -c "corepack enable &&
             yarn install --immutable || yarn install &&
             yarn dev --host 0.0.0.0 --port 5173"
